### ISSUE TITLE
Remove confusing gh-pages branch

### ISSUE THREAD

**Issue by redtide** [jackaudio/jackaudio.github.com#106]
Despite the fact that an [organization pages branch] doesn't work from a gh-pages branch like normal users accounts, the current (old) gh-pages branch is confusing, mainly for those who are forking the project and use their own gh-pages branch to display their version of the website in their user accounts.

As example I could use the master branch too but if it has a CNAME it gives an error so ATM I can't use the it on my side and I had to delete the gh-pages branch to have my version of the master one.

It could be replaced by a tag instead to keep it in history, or at least renamed (I vote for the former option if possible).

[organization pages branch]: https://help.github.com/en/github/working-with-github-pages/about-github-pages#publishing-sources-for-github-pages-sites

**Comment by falkTX** [comment]
I removed it just now, indeed we do not use it anymore and can be confusing

**Comment by redtide** [comment]
Great, thanks!
