### ISSUE TITLE
Missing link in FAQ

### ISSUE THREAD

**Issue by computersarecool** [jackaudio/jackaudio.github.com#118]
The number one option in the FAQ on how to use Pulse Audio and JACK together suggests: Checking out the "How do I route audio to/from …” section of the FAQ."

This section does not exist in the FAQ.

A good thing would be to link directly to the (missing) section, rather than pointing people to the entire FAQ and asking them to find a section.

**Comment by redtide** [comment]
It seems to me that the point here is that the main page of the FAQ is just an index page that points to other related pages, and the relevant one you are mentioning has a list of options on its own, so not really a page/section by itself.
The "section" is "How can I play audio from …. via JACK?", which presents the various "Flash", "Gstreamer", "xmms" etc options.
So IDK what to do here more than renaming the "How do I route audio to/from …” and "section" to "How can I play audio from …. via JACK?" and "list item" (or something).

**Comment by redtide** [comment]
The [FAQ is here], I suppose you are referring to the [WIKI] (which points on the former at the beginning).
The section is meant to be the "How can I play audio from …. via JACK?" list item that has sub-items as various solutions as options.
The only problem I see here is that the WIKI is a redundant place where the website should be the main reference.

[FAQ is here]: https://jackaudio.org/faq/
[WIKI]: https://github.com/jackaudio/jackaudio.github.com/wiki/FAQ_and_Myths

**Comment by computersarecool** [comment]
I see. Yes - sorry the wording of that particular FAQ portion was confusing to me. This makes sense now.

Thanks

**Comment by redtide** [comment]
YW. Thank you for the report, I think the Wiki will be merged with the website soon to avoid confusion.
