### ISSUE TITLE
jack audio working without sound card

### ISSUE THREAD

**Issue by blueskyltx** [jackaudio/jackaudio.github.com#123]
There is no sound card on my computer, can I use jack audio to capture Skype's output audio, save as files, and playback audio to Skype? Is there any reference documents?

**Comment by falkTX** [comment]
This project you reported the ticket on is regarding the jack website, not for regular questions. (use the mailing list for that)

In any case, Skype does not support JACK .
Assuming you are using Linux, you can try to do something with pulseaudio. JACK won't help much here, only make it more complex.
