### ISSUE TITLE
"Jack: data not valid" when using higher channels count (MTU bound?)

### ISSUE THREAD

**Issue by lapsio** [jackaudio/jackaudio.github.com#124]
Hi

I'm using Scarlett 18i20 which (as name suggests) is 18/20 channels ADAT interface. Unfortunately I can't seem to successfully connect it over network using more than 6/6 channels. When I bump MTU to 9000 (max jumbo supported by my physical network) and use `-m 9000` flag I can reach 8/8 channels. If I use virtualized network (with no real MTU limit) I can reach 10/10 channels with 18k jumbo (which is realistically not supported by real world hardware). It's quite weird limitation.

As result It's quite problematic to use this interface via netjack. Even though I have actually 10G network backbone which should be easily able to pull off such scenario.

I tried increasing `-n` and even adding `-R` and `-D` but nothing helped. My JACK package is crashing with segmentation fault when I try to use CELT compression but honestly I wouldn't accept this as solution anyways so I guess it doesn't really matter.

**Comment by trebmuh** [comment]
This repo is meant for the website. If you need assistance with jack, please, use the [jack 1](https://github.com/jackaudio/jack1) or the [jack 2](https://github.com/jackaudio/jack2) repos.
