### ISSUE TITLE
[Windows 32 Bits] jack2-win-32-v1.9.15.exe is not a win32 valid application

### ISSUE THREAD

**Issue by E-Gwen** [jackaudio/jackaudio.github.com#133]
Hi,

When I try to install J.A.C.K 1.9.15, I get this error message : 

"D:\jack2-win-32-v1.9.15.exe n'est pas une application win32 valide"

        ("D:\jack2-win-32-v1.9.15.exe is not a win32 valid application")

As I want to try Carla 2.2 with no SSE build and Ardour 6.3 with Windows XP, don"t you think it will be appropriate to make a jack release compatible with this OS ?

Notice that J.A.C.K. 1.9.11 32 bit version is running fine.

Best regards.

E-Gwen.

**Comment by E-Gwen** [comment]
Sorry, i just saw the message "don't post issue for jack here".

I go to the right place.

**Comment by falkTX** [comment]
yes please, thanks
