### ISSUE TITLE
Cross Platform virtual audio cable

### ISSUE THREAD

**Issue by ShuoShen-Susan** [jackaudio/jackaudio.github.com#140]
Oh, hi~dear

Thanks for your great work. Sounds super!
Recently, I want to make software, which could process the voice input from the computer and sent results to other desktop software. Somehow like a virtual audio cable. When you download it, other software, like zoom, would recognize it as an audio card.
I want to know if the JACK works for this kind of software? And which programming language need for Jack? Could I use python?
Thanks for your reading. Hope you have a nice day~

Susan

**Comment by falkTX** [comment]
JACK will not work as virtual soundcard, better find something else.

**Comment by mxmilkiib** [comment]
There is however https://jackaudio.org/faq/netjack.html which might allow for what is desired.
