### ISSUE TITLE
Is available for virtual audio cable?

### ISSUE THREAD

**Issue by ShuoShen-Susan** [jackaudio/jackaudio.github.com#141]
Oh~hi,
Thanks for your great work. Sounds super!
Recently, I want to make a software, which could process the voice input from the computer and sent results to other desktop software. Somehow like a virtual audio cable. When you install it, other software, like zoom, would recognize it as an audio card. Anyone knows is Jack available for this kind of virtual audio cable?
Also, Could I use Jack in other languages except for C++?
Susan

**Comment by falkTX** [comment]
Please dont report the same issue multiple times, thanks.
This is not a user forum, this is for issues regarding the website.

If you want some assistance or randomly ask stuff, please do so at one of the community channels listed at https://jackaudio.org/community.html
