### ISSUE TITLE
Use GH Actions to build pages

### ISSUE THREAD

**Issue by redtide** [jackaudio/jackaudio.github.com#144]
After a recent discussion about some difficulties by using a fixed version of Ruby/Jekyll to satisfy the GitHub Pages requirements,
I thought that this could make things easier, something I added recently also for the [sfizz] website:
- Use more recent Ruby and Jekyll with custom plugins if needed
- The built pages will go on a [www] (or other name of choice) orphan branch, with a single force pushed commit
- The `api` directory can be removed from git and added to `.gitignore`, built in CI and force pushed on the other branch
- Forks will use the same workflow, with a related `baseurl` for correct links

If OK I'll post a PR.

[sfizz]: https://github.com/sfztools/sfztools.github.io/blob/master/.github/workflows/build.yml
[www]: https://github.com/sfztools/sfztools.github.io/tree/www

**Comment by redtide** [comment]
Not using a specified Ruby version means that you can use the latest available on your system instead having to deal with a Ruby manager like rbenv or RVM, this should make life easier also to any contributor that would like to test their changes locally.
T
he api directory is not made by source files, they are built files with doxygen from jack1 sources just like the html pages from markdown files, so it is not necessary pollute the git history of html stuff, they go directly on the "build" branch.

**Comment by falkTX** [comment]
hmm why close this?

**Comment by redtide** [comment]
> the proposed changes (from what I understand) will not help with that.

Because I'm tired of discussing when people looks hostile to propositions before understand/discussing them.

**Comment by falkTX** [comment]
I was asking questions, because I dont understand the changes. I am sorry I did not mean to be hostile.

**Comment by falkTX** [comment]
> > the proposed changes (from what I understand) will not help with that.
> 
> Because I'm tired of discussing when people looks hostile to propositions before understand/discussing them.

I mean, the changes you propose do not help me at understanding ruby, which was/is the main issue for running the site locally. Nothing you do from your side is going to really change that, I will keep being stupid in regards to Ruby until I take time to study and use it. Nothing else I use needs ruby though...

If you think this is a worthwhile addition I can just take your word for it. Should we merge it?
I am still not sure how much of an opinion you want from me.
