### ISSUE TITLE
ladish wannabe-deprecation

### ISSUE THREAD

**Issue by nedko** [jackaudio/jackaudio.github.com#160]
The wiki states that somehow ladish and lash are deprecated. As jack project (active and that used to push jack session *protocol*), is different from lash project, and ladish project (maintained), such statement is invalid and incorrect at least, if not offensive, given all the maligned behaviour I've personally seen (unfortunately). To reiterate JACK project has no authority on matters not defined by it.

I kindly ask the author of the commit to remove such technically incorrect and substantially defamatory (at least toward LADISH) statement.

commit 560d3b8d42f9d47f6c78c5d002e6f1456d3949ee
Author: Milkii Brewster <github@milkmiruku.com>
Date:   Mon Nov 2 21:26:53 2020 +0000

    ## Session Management Both LASH/LADISH and JACK Session are deprecated; the use of [NSM](https://linuxaudio.github.io/new-session-manager) is recommended.

**Comment by falkTX** [comment]
I think it is safe to call something deprecated when its last official release was more than 10 years ago.
the ladish site was also down for quite a fair bit of time, it is natural for people to think the project was abandoned.

no ill intent there, it was just the state of the matter.

if you want to keep working on ladish and somewhat "revive" it, you are free to do so.
but without a new release, people wont see it as active. regular users do not check git commits after all

**Comment by nedko** [comment]
I *do* see defamatory ill intent.

**Comment by mxmilkiib** [comment]
Maybe you're hypermentalising

**Comment by nedko** [comment]
You are misusing JACK github (or otherwise) organization for promoting defamation against LADISH project. This is unethical, and as moral rights do exist in some jurisdictions, illegal. Assumption of upstream availability combined with lack of help in form of patches to adjust build system issues induced by newer distros and combined with winning that upstreams should fix downstream problems like this is not same as lack of maintenance. Appeal to nature being mentioned is quite often considered another logical fallacy. As for your cultural bias, we all have them.

Please remove the defamatory statement.

**Comment by falkTX** [comment]
there has been more than enough discussion about this.
I am tired of it tbh. people have moved on to NSM when other projects had almost no visible activity at all.

also, this is getting into paranoia territory. I dont see any fruitful discussion that can possibly come from this at this point in time.

**Comment by nedko** [comment]
I've just found that build scripts for jack2 are testing debian packaging in form of build.yml. I'm dealing with this issue in LADI project, but it may deserve a dedicated issue in context of jackaudio project. As why Debian specifics are pushed by upstream. There are clearly other package managers in use. I personally run Gentoo.

**Comment by nedko** [comment]
The LADI fixes for the build.yml that make the build stage not requiring Ubuntu Studio packaging can be found here:
https://github.com/LADI/jack2/commit/cbb9c88549d7fedf15f9a70f78267113769c5651
https://github.com/LADI/jack2/commit/110d447299277c6393a51c73153b5c2f27f58151

I am willing to create a pull request that combines the two and are mergeable instead of cherry-pick-able.

**Comment by eeickmeyer** [comment]
> UPDATE: It appears that jackaudio project is doing QA for Ubuntu Studio project. In such context of jackaudio being sub-project of Ubuntu Studio it makes sense to deprecate ladish. Ubuntu Studio, as distributor can deprecate ladish if it was distributed before by Ubuntu Studio. Applying this logic however implies that jackaudio.org is sub-project of Ubuntu Studio. As I argue that jackaudio is upstream project, the whole deal seems to be mixing of definition of upstream and downstream for unknown to me reasons and seems to be linked in the the tarball argument of the defamation offenders. The things are a bit more irritating, given that Debian based distributions also have practice of packaging git versions. They could apply policies whether to require tarballs or accept git, but they should not result in such misuse of jackaudio.org, unless it is indeed a sub-project of Ubuntu Studio.

Leader of Ubuntu Studio here. This is completely and unequivocally wrong. At no point has jackaudio done any QA for Ubuntu Studio, implied or otherwise.

**Comment by nedko** [comment]
As of now [1], this can be seen: https://github.com/jackaudio/jack2/blob/master/.github/workflows/build.yml#L295

https://github.com/jackaudio/jack2/commit/88102ec4a73ecb18b58198193905aefe6b378ce5

**Comment by ghard** [comment]
A regular Jack user here. For me, having a widely adopted, consistent, and maintained session management system would be great!

I can see the point in saying that Jackaudio has no right in stating that ladish - an individual externally developed session manager - is deprecated, as it's not a Jackaudio project.

However, they are free to endorse whichever system they see as a better (as in technically better, or more actively maintained) option. As was pointed out, from the viewpoint of a regular user, ladish hasn't really been going anywhere for quite some time.

So... we're really wasting time on semantics here - use "not recommended by Jackaudio developers in its current state" rather than "deprecated" and review that judgement if indeed ladish later proves to again be relevant - both by technical excellence and penetration.

**Comment by falkTX** [comment]
I will remove ladish from the wiki and site, but jack-session still remains deprecated in favour of the much better NSM protocol and server tools (be it non-session-manager, new-session-manager, raysession, argodejo or any other I am not aware of).

**Comment by falkTX** [comment]
also, the CI checks are just extra things put in place to ensure things dont break between releases.
there are checks for freebsd too, because why not, it does not have to mean involvement of that other party (though in the case of freebsd it does).

in a similar fashion, the jack-example-tools has tests for a wide range of distros and even checks build against pipewire. see https://github.com/jackaudio/jack-example-tools/blob/main/.github/workflows/build.yml
it is just an extra CI step, means nothing but what it is - a build test

**Comment by eeickmeyer** [comment]
> So... we're really wasting time on semantics here - use "not recommended by Jackaudio developers in its current state" rather than "deprecated" and review that judgement if indeed ladish later proves to again be relevant - both by technical excellence and penetration.

@ghard I agree. This is really just an argument in semantics here and no ill will was intended.

> I do see defamatory ill intent.

@nedko No. Instead of straight-up assuming bad-faith and attacking, try coming into situations assuming good faith instead. I'm 100% positive no ill will was intended here.

**Comment by falkTX** [comment]
the wiki related text has been changed, and ladish is no longer mentioned.
a quick search via github for "ladish" on the jackaudio org shows no mentions https://github.com/search?q=org%3Ajackaudio+ladish

I consider the issue fixed.

**Comment by nedko** [comment]
@eeickmeyer I tried rising this issue on numerous times on IRC and what I've seen is anything but good faith.

I consider this issue to be fixed as well. Thank you.
