### ISSUE TITLE
JACK Metadata URLs missing

### ISSUE THREAD

**Issue by mseeber** [jackaudio/jackaudio.github.com#19]
From the mailing list:
(2) then add in the fact that well known metadata "keys" were discussed there, and the idea is for well-known ones to be URIs that resolve to actual URLs where someone could actually read a description of what the data is. So for example, we did decide upon http://jackaudio.org/metadata/* as an "official" namespace, and there was wide support for http://jackaudio.org/metadata/pretty-name and http://jackaudio.org/metadata/role (although the 2nd one needs a vocabulary which is not currently defined).  
Unfortunately when we "lost" the drupal jackaudio site due to hacking earlier this year, we lost the metadata/ part of the website, so the URIs do not function as URLs right now.

archive.org link:
http://web.archive.org/web/20140328210350/http://jackaudio.org/metadata

**Comment by SpotlightKid** [comment]
I've resurrected the contents of the above mentioned page from the wayback machine and put it in the current Github Wiki: https://github.com/jackaudio/jackaudio.github.com/wiki/JACK-Metadata-API

**Comment by piegamesde** [comment]
Has anyone resurrected the content of the actual `http://jackaudio.org/metadata/*` pages? I could not find anything on Archive.org. Otherwise, I'll simply paste the current code documentation of those properties because having 404s here is pretty bad.

**Comment by falkTX** [comment]
I forgot about resurrecting that page, lets see if just adding the folder there works..

**Comment by falkTX** [comment]
I manually wrote the pages for now.
Stuff like https://jackaudio.org/metadata/pretty-name shows something when you open it in a browser :)

**Comment by SpotlightKid** [comment]
I'm pretty sure there weren't actually any pages there except the one I restored. At least I found no evidence for their existence.
