### ISSUE TITLE
Ubuntu 14.04 - double tracks - one without jack audio started, one with guitarix - line 6 gx

### ISSUE THREAD

**Issue by maskonietka** [jackaudio/jackaudio.github.com#24]
Hi,

I have a bit problem with double voice ( duble tracks ). I've got Ubuntu 14.04 and line 6 POD gx.

Everything for Line 6 is installed, working fine, but when I plug in POD gx I've got one track - clear - jack audio is not on yet. Laptop sound card is automatically muted.
After I will turn on jack audio and guitarx I have two tracks - one from system ( clear ) and one from guitarx, so it cause distortion in my headphones.

I checked alsamixer also, laptop sound card is muted, line 6 has PCM and Volume, when I try to turn some of them down everything is muted.

Does anyone fight with similar problem before ?

**Comment by mseeber** [comment]
Sorry for the late answer.
For this kind of question, you will probably have more luck on the linuxaudio mailing lists or irx channel, as this repository only represents the jackaudio homepage.
