### ISSUE TITLE
Jack and Cygwin

### ISSUE THREAD

**Issue by halbius** [jackaudio/jackaudio.github.com#34]
Hi everybody,

I'm trying to install software on a windows system that uses jack. Jack is allready installed from the binaries. This new piece of software needs to be build from source, therefore I use cygwin.
When running the ./configure script it fails with the error:

> configure: error: Package requirements (jack >= 0.118.0) were not met:
> 
> No package 'jack' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables JACK_CFLAGS
> and JACK_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.

I was trying to adjust the PKG_CONFIG_PATH, but with no result.
I was trying to reinstall jack from within cygwin using apt-cyg, but it didn't find any jack stuff.

Can anybody give me a hint how to solve this?

Thanks a lot!

**Comment by mseeber** [comment]
For issues regarding JACK2 itself, please use the bugtracker of:
https://github.com/jackaudio/jack2 (I assume you use JACK2, if you are on windows)
or refer to the jack-devel mailing list.
https://github.com/jackaudio/jackaudio.github.com/wiki/MailingLists
