### ISSUE TITLE
Add Praxis LIVE to applications list

### ISSUE THREAD

**Issue by mseeber** [jackaudio/jackaudio.github.com#40]
On 04/03/2016 01:21 PM, Neil C Smith wrote:
Any chance of adding in Praxis LIVE (www.praxislive.org)?  Not sure of
the best category for it mind you.

**Comment by Jee-Bee** [comment]
I was scrolling today trough the application list and i figured out some programs / tools that haven't been update in about 10 years...
Idea to add a column with latest release date?

**Comment by redtide** [comment]
> Idea to add a column with latest release date?

FWIW that list looks to me unmaintainable already as is, I can't imagine who have the time also to keep it updated with all application releases...

I gave a look to this specified application and JACK support is optional, not a big addition so I wonder if this issue could be even closed.

**Comment by trebmuh** [comment]
Added Praxis in the same category than PureData.

@Jee-Bee : please, open another new issue instead of _hijacking_ one with a different topic/subject. Thank you.
