### ISSUE TITLE
add language bindings

### ISSUE THREAD

**Issue by rhetr** [jackaudio/jackaudio.github.com#56]
language bindings should be included for interested developers.
## rust

https://github.com/psantacl/rusty-jack
https://github.com/nicklan/rust-jack
https://github.com/Boddlnagg/jack-sys
https://github.com/wmedrano/rust-jack
## python

https://jackclient-python.readthedocs.io/en/0.4.1/
## golang

https://github.com/xthexder/go-jack
## haskell

https://wiki.haskell.org/JACK

**Comment by mseeber** [comment]
* jack-sys has apparently died already, removing it from the list to add...

* rusty-jack seems abandoned since 2013 and since rust still evolves, it is probably not a good choice.

**Comment by mseeber** [comment]
done in 182c20deaae85e4be68679ffbaf4b625c123cdeb
