### ISSUE TITLE
Help with a bug

### ISSUE THREAD

**Issue by marksev1** [jackaudio/jackaudio.github.com#57]
Can you guys help me with this error:

[jack.c:252] error: Failed to open jack client: 0x1 [jack.c:58] warning: FIXME: One needs to wait or write some silence here to prevent the last bits of audio to vanish out of the ringbuffer. 

Its from a python script, I'm using Alsa. If i try mpg123 from the commandline it just works, while from the python scripts it errors out.

**Comment by mseeber** [comment]
This Bugtracker is intended to be used only for reports regarding the jackaudio.org homepage.
For questions or bugreports regarding JACK, please use the mailinglist, the respective bugtrackers of jack1 or jack2 or the IRC channel.
You may find these here:
http://jackaudio.org/community.html
