### ISSUE TITLE
Jakcd has to be started mannually on XP, before invoking JAck Control.

### ISSUE THREAD

**Issue by afarlie** [jackaudio/jackaudio.github.com#58]
I've found that when running on my install of XP ( on a PC which has an oboard Realtex chipset), I've found I've had to start the port audio server manually, or Jack Control says it's not been able to connect.

I assume there is a reason for this behaviour?

**Comment by mseeber** [comment]
This bugtracker is intended to be used only for reports regarding the jackaudio.org homepage.

For questions and bug reports regarding JACK, please use the mailing list, the respective bug trackers of [jack1](https://github.com/jackaudio/jack1) or [jack2](https://github.com/jackaudio/jack2) or the IRC channel.
You may find out where to get help here:
http://jackaudio.org/community.html

As your report does not relate to the jackaudio.org homepage, I close this report.
