### ISSUE TITLE
move some page out of FAQ dir

### ISSUE THREAD

**Issue by mseeber** [jackaudio/jackaudio.github.com#6]
...and think about restructuring the main menu/layout

fewer pages would be nice for overview, but the old content seems to be worth keeping.

applies to:
- [x] email.md
- [ ] documentation.md
- [ ] build_info.md

and maybe more

**Comment by redtide** [comment]
Outdated. Other than that the FAQ section might have outdated information and indeed some page should be moved out from there like instructions to how to use/install/uninstall JACK on Windows (if still necessary), but still this is what this documentation repository is about, to be kept updated, so part of the work in progress.
