### ISSUE TITLE
JACK brakes other applications which rely on cmd (Windows)

### ISSUE THREAD

**Issue by johannesspohr** [jackaudio/jackaudio.github.com#60]
It seems that the jack cmd binary replaces the native shell, which can lead to other programs not working anymore (WinSCP and putty in my case). I'm running windows 10 with the "new" shell activated.

**Comment by mseeber** [comment]
This bugtracker is intended to be used only for reports regarding the jackaudio.org homepage.

For questions and bug reports regarding JACK, please use the mailing list, the respective bug trackers of [jack1](https://github.com/jackaudio/jack1) or [jack2](https://github.com/jackaudio/jack2) or the IRC channel.
You may find out where to get help here:
http://jackaudio.org/community.html

As your report does not relate to the jackaudio.org homepage, I close this report.
