### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by mefjuu** [jackaudio/jackaudio.github.com#65]
Links to Windows binaries are broken: http://jackaudio.github.io/downloads/

**Comment by lasconic** [comment]
Not sure who is in charge of the website, but you could maybe request some free storage to OSUOSL and store the binaries there.

**Comment by mseeber** [comment]
This is a known problem.
The releases are managed by @sletz, who is also in charge of providing the binaries, so I think he is going to decide where to host the binaries.

**Comment by brownerthanu** [comment]
This is causing a problem with a time-sensitive project I'm working on. Would really appreciate if this would be fixed quickly.

**Comment by michaelmaw** [comment]
Is there any way to download the Windows binaries from another link? I wanted to try out Jack with Musescore, but no downloads available...

**Comment by mseeber** [comment]
Apparently you could use the version included with Radium:
https://github.com/jackaudio/jack2/issues/258#issuecomment-289663637

**Comment by ssfrr** [comment]
also now downloadable from github: https://github.com/jackaudio/jackaudio.github.com/releases

**Comment by michaelmaw** [comment]
Great! That link works.

**Comment by lordcheeto** [comment]
It would be best if the releases were in their respective repos (e.g. https://github.com/jackaudio/jack2/releases), since this makes it impossible to tell which commits the releases were based on.

**Comment by lordcheeto** [comment]
The source downloads are also for this repo, since they are built off tags in this repo.

**Comment by mseeber** [comment]
This is a known issue, I will see if I can convince people to attach the binaries to the jack2 repo.

**Comment by falkTX** [comment]
afaik the download links work now. please confirm so we can close this issue.
(the binaries are in the wrong place I guess, but that's a minor thing. will be solved with new releases anyway)

good news though - I have access to jackaudio.org now, so I can update the website when needed.
ping me on irc and I'll update it quickly.

**Comment by michaelmaw** [comment]
Confirmed. Links work now. Thanks!

**Comment by falkTX** [comment]
Alright, thanks for confirming. I'm closing the bug then.
