### ISSUE TITLE
Build fails with JACK2 on Arch Linux 2017.02.01

### ISSUE THREAD

**Issue by MoonriseWarrior** [jackaudio/jackaudio.github.com#68]
Hello,

I've been trying to install JACK2 with the D-Bus support on the aforementioned system, however I get a lot of errors and the build fails. I do not think that this has anything to do with the version of Arch I am running because all other apps install fine and my kernel and AUR are up-to-date.

I get the following in stdout:
```
Waf: Entering directory home/user/jack2/build$
[ 71/266] Compiling tests/test.cpp$
Waf: Leaving directory /home/user/jack2/build$
```

Which is followed by the following in stderr:
https://paste.pound-python.org/show/uKSE2YgbpkQKWOftbl1S/

Can anyone help? I was following the commands exactly as shown in the wiki (git clone, waf configure --dbus, waf build, waf install). The first two mcommands finished just fine, so I have not included them.

Thanks,
Matt

**Comment by mseeber** [comment]
This bugtracker is intended to be used only for reports regarding the jackaudio.org homepage.

For questions and bug reports regarding JACK, please use the mailing list, the respective bug trackers of [jack1](https://github.com/jackaudio/jack1) or [jack2](https://github.com/jackaudio/jack2) or the IRC channel.
You may find out where to get help here:
http://jackaudio.org/community.html

As your report does not relate to the jackaudio.org homepage, I close this report.
