### ISSUE TITLE
In Wiki, change "remove QJackCtl if you use that and install Cadence..." to "Instead of using QJackCtl, install Cadence..."

### ISSUE THREAD

**Issue by MarioMey** [jackaudio/jackaudio.github.com#76]
Here: https://github.com/jackaudio/jackaudio.github.com/wiki/WalkThrough_User_PulseOnJack

By saying "remove QJackCtl", it seems that it is necessary and obligatory to remove that program. And it is not like this. I installed Cadence, I think I'm going to start using it, instead of QJackCtl... but I didn't remove QJackCtl. I don't want to and it is not necessary.

It's confusing like it is now.

Sorry if this "issue" doesn't correspond here...

**Comment by mseeber** [comment]
That particular section was added by @mxa . Any comments on the rationale behind uninstalling qjackctl?

**Comment by mxa** [comment]
Back in the day it was my experience that they interfere, tried it now and it seems they can coexist.

**Comment by mseeber** [comment]
I removed the recommendation to uninstall qjackctl. Thank you for bringing this up and for the quick response.
