### ISSUE TITLE
rtprio 99 is too high

### ISSUE THREAD

**Issue by dvzrv** [jackaudio/jackaudio.github.com#77]
the rtprio [suggested](http://jackaudio.org/faq/linux_rt_config.html) is too high IMHO, as there are watchdogs and migrations running at 99.
Debian defaults to 95, but I guess something around 98 should be fine.

**Comment by mseeber** [comment]
I agree that a normal RT application should depending on the system run at 90 or 95 but these limits just limit what is possible for the user group to run.
For this exact use case this watchdog you mentioned might want to run at 99 under the mentioned group.
It depends on what is supposed to be achieved here. I have to read the article completely to be able to pass judgement on that later, i am aware though that at least rhel and debian do provide defaults for user groups with rt permissions.

**Comment by crocket** [comment]
90 is fine.

**Comment by falkTX** [comment]
Fixed in 1ff76e5db9493c172a101fb283b091d31b90bb9d

**Comment by falkTX** [comment]
I need to setup my dev machine to use a newer Ubuntu version, so the website is not updated yet.
Once I do the update, then we will see the html updated. If someone is in a rush, PR that just regenerates html contents is welcome (follow instructions on README)
