### ISSUE TITLE
retrieve uploaded content from old page

### ISSUE THREAD

**Issue by mseeber** [jackaudio/jackaudio.github.com#8]
There is uploaded content, like documentation PDFs, screenshots and stuff like that, which is linked in the page but not included in the new Page yet.

Example
in 'pulseaudio_and_jack.md' is a link to a screenshot which needs to be corrected, after the screenshot is included.

**Comment by redtide** [comment]
I removed the mentioned link which, if still the same one about QJackCtl, was not available and also specific to one UI application. Who knows now which pdf docs and images those was and where they are gone? I have found nothing in the git history.
