### ISSUE TITLE
Please update and regenerate documentation

### ISSUE THREAD

**Issue by diovudau** [jackaudio/jackaudio.github.com#81]
The official docs on the website are from 2014

I just wasted several hours with jack_get_all_properties where the docs say "Set to a NULL-terminated array of descriptions" and returns 0 on success. But it returns a counter and there is no NULL termination.

http://www.jackaudio.org/files/docs/html/group__Metadata.html#ga539718c59d8a1fe68ed006e2699221df

**Comment by redtide** [comment]
Outdated and no more valid (different page and function description), closing.
