### ISSUE TITLE
scientific publications on the design of Jack?

### ISSUE THREAD

**Issue by jwaldmann** [jackaudio/jackaudio.github.com#84]
Are there scientific publications on JACK (peer-reviewed, preferrably not paywalled) and could you list them on the web site? What is recommended reading to understand: 
1. what problem does JACK solve, 
2. and how?  

I know that brief answers are given 
1. on the jackaudio.org landing page, 
2. on http://www.jackaudio.org/api/#jack_overview

I am asking because I plan to present JACK in my lecture on computer music.

**Comment by mseeber** [comment]
There are some references in past Linux Audio Conference proceedings which are available in PDF format.
You can find the proceedings at the LAC homepages, for example: https://lac.linuxaudio.org/2013/
Just change the year, i think there is also a overview somewhere.
Id did reconstruct some of the history and details especially about the development of jack2 from previous LAC proceedings, from the top of my head, the 2007 one may be interesting.
