### ISSUE TITLE
Unable to use jack realtime

### ISSUE THREAD

**Issue by ranjithshegde** [jackaudio/jackaudio.github.com#89]
Greetings,
I recently installed jack1 and 2 to help with supercollider on Ubuntu 18.04LTS and when I launch the server I get the following jack related issue.

01:23:24.119 Statistics reset.
01:23:24.147 ALSA connection change.
01:23:24.242 D-BUS: Service is available (org.jackaudio.service aka jackdbus).
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
01:23:24.354 ALSA connection graph change.
01:23:30.451 D-BUS: JACK server could not be started. Sorry
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Fri Apr 12 01:23:30 2019: Starting jack server...
Fri Apr 12 01:23:30 2019: JACK server starting in realtime mode with priority 10
Fri Apr 12 01:23:30 2019: self-connect-mode is "Don't restrict self connect requests"
Fri Apr 12 01:23:30 2019: ERROR: Cannot lock down 82280346 byte memory area (Cannot allocate memory)
Fri Apr 12 01:23:30 2019: Acquired audio card Audio0
Fri Apr 12 01:23:30 2019: creating alsa driver ... hw:0|hw:0|1024|2|44100|0|0|nomon|swmeter|-|32bit
Fri Apr 12 01:23:30 2019: ERROR: ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
Fri Apr 12 01:23:30 2019: Released audio card Audio0
Fri Apr 12 01:23:30 2019: ERROR: Cannot initialize driver
Fri Apr 12 01:23:30 2019: ERROR: JackServer::Open failed with -1
Fri Apr 12 01:23:30 2019: ERROR: Failed to open server
Fri Apr 12 01:23:31 2019: Saving settings to "/home/ranjith/.config/jack/conf.xml" ...
01:23:44.249 Could not connect to JACK server as client. - Overall operation failed. - Unable to connect to server. Please check the messages window for more info.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

Would anyone be able to assist me with this please?

**Comment by trebmuh** [comment]
This is the repository for the website. You might want to use [other point of contact](https://jackaudio.org/community.html).
