### ISSUE TITLE
no ssl on website

### ISSUE THREAD

**Issue by mxa** [jackaudio/jackaudio.github.com#94]
the page currently looks broken for people with the HTTPS Everywhere extension installed because it will redirect to a non existing https version of the site.

**Comment by falkTX** [comment]
paging @pauldavisthefirst for this

**Comment by mxa** [comment]
Alternatively I could open an issue at [https://github.com/EFForg/https-everywhere/issues](https-everywhere) to have jackaudio.org excluded from URL redirecting. Preferably though SSL would work.

**Comment by redtide** [comment]
This should be solved by recent changes.

**Comment by falkTX** [comment]
it was solved before too. just was not aware of this issue being open. we close it now
