### ISSUE TITLE
Using ALSA loopback, alsa_in, and alsa_out is a bad way to bridge JACK and ALSA.

### ISSUE THREAD

**Issue by crocket** [jackaudio/jackaudio.github.com#97]
http://jackaudio.github.io/faq/routing_alsa.html points to https://alsa.opensrc.org/Jack_and_Loopback_device_as_Alsa-to-Jack_bridge

Using ALSA loopback, alsa_in, and alsa_out introduces too many imperfections in audio.
I often heard a lot of pops, crackles, and clicks in audio from ALSA loopback.

For months, I worked on a perfect way to bridge JACK and ALSA through a USB soundcard and zita-ajbridge instead of ALSA loopback, alsa_in, and alsa_out.

Some days ago, I found a perfect way which can still be improved.

Read [The best way to bridge ALSA and JACK that I found.](https://www.linuxmusicians.com/viewtopic.php?f=27&t=20419&p=110059)

Although I decided that this setup was a giant overkill for my use case, this can be helpful to others.

In my case, I just needed a reliable morning alarm. Instead of buying one, I built one by sharing a pair of passive speakers between Raspberry Pi 3 B+ and my workstation computer. Raspberry Pi 3 B+ was used solely as a morning alarm. It was a giant overkill. I'm going to replace Raspberry Pi 3 B+ and its I2S DAC amplifier with a USB DAC amplifier for my workstation computer and buy a portable alarm clock.

**Comment by falkTX** [comment]
The bridge is not perfect, but works for many people.
I am sorry it did not work for you, but no reason to spam the same thing everywhere you can find a place to write about it.

**Comment by crocket** [comment]
I think it's beneficial to let people know how I removed imperfections on http://jackaudio.github.io/faq/routing_alsa.html
