### ISSUE TITLE
www.jackaudio.org DNS record missing

### ISSUE THREAD

**Issue by xkr47** [jackaudio/jackaudio.github.com#99]
A lot of google hits refer to the http://www.jackaudio.org/ domain but there is currently no DNS record for it. Therefore users get a browser error about not finding the site.

http://jackaudio.org/ works fine but that doesn't help for existing urls having the `www.` prefix.

**Comment by redtide** [comment]
This should be solved now.

**Comment by xkr47** [comment]
As a side note, https does not work but I suspect google might infer from the 301 on the http side that it should update its links

**Comment by redtide** [comment]
Now pages are hosted by GH directly with forced HTTPS, so it should be Let's encrypt enabled.
